[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "scikit-build",
    "cmake>=3.20",
    "ninja",
    "pybind11>=2.6"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["python/tests"]
addopts= "-v --cov=./ --cov-report=xml"