#include "cle.hpp"

#include <algorithm>
#include <assert.h>
#include <random>

template <class type>
auto
run_test(const std::array<size_t, 3> & shape, const cle::mType & mem_type) -> bool
{
  std::vector<type> input = { 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1 };
  std::vector<type> kernel = { 1, 0, 0, 0, 1, 0, 0, 0, 1 };
  // this is the output generated by scipy.ndimage.convolve(input, convolve_kernel, mode='nearest')
  std::vector<type>           valid = { 3, 1, 0, 0, 1, 4, 0, 0, 0, 0, 4, 1, 0, 0, 1, 4 };
  const std::array<size_t, 3> kernel_shape = { 3, 3, 1 };

  auto device = cle::BackendManager::getInstance().getBackend().getDevice("", "all");
  auto gpu_input = cle::Array::create(shape[0], shape[1], shape[2], cle::toType<type>(), mem_type, device);
  auto gpu_kernel =
    cle::Array::create(kernel_shape[0], kernel_shape[1], kernel_shape[2], cle::toType<type>(), mem_type, device);
  gpu_input->write(input.data());
  gpu_kernel->write(kernel.data());

  auto gpu_output = cle::tier1::convolve_func(device, gpu_input, gpu_kernel, nullptr);

  std::vector<type> output(gpu_output->size());
  gpu_output->read(output.data());

  return std::equal(output.begin(), output.end(), valid.begin()) ? 0 : 1;
}

auto
main(int argc, char ** argv) -> int
{
  cle::BackendManager::getInstance().setBackend("opencl");
  std::cout << cle::BackendManager::getInstance().getBackend() << " backend selected" << std::endl;
  assert(run_test<float>({ 4, 4, 1 }, cle::mType::BUFFER) == 0);

  cle::BackendManager::getInstance().setBackend("cuda");
  std::cout << cle::BackendManager::getInstance().getBackend() << " backend selected" << std::endl;
  assert(run_test<float>({ 4, 4, 1 }, cle::mType::BUFFER) == 0);

  return EXIT_SUCCESS;
}