#ifndef __cleKernelList_h
#define __cleKernelList_h


// #include "cleSmallerOrEqualConstantKernel.h" 
// #include "cleSetKernel.h" 
// #include "cleMaximumZProjectionKernel.h" 
// #include "cleCopyKernel.h" 
// #include "cleGreaterOrEqualConstantKernel.h" 
// #include "cleDilateSphereKernel.h" 
// #include "cleSetNonzeroPixelsToPixelindexKernel.h" 
// #include "cleDetectMaximaKernel.h" 
// #include "cleMinimumYProjectionKernel.h" 
// #include "cleEqualKernel.h" 
// #include "cleSmallerOrEqualKernel.h" 
#include "cleAddImageAndScalarKernel.h" 
// #include "cleConnectedComponentLabellingBoxKernel.h" 
// #include "cleSumYProjectionKernel.h" 
// #include "cleSumOfAllPixelsKernel.h" 
// #include "cleBlockEnumerateKernel.h" 
// #include "cleSumZProjectionKernel.h" 
// #include "cleAddImagesWeightedKernel.h" 
// #include "cleMinimumOfAllPixelsKernel.h" 
// #include "cleGreaterOrEqualKernel.h" 
#include "cleMeanBoxKernel.h" 
// #include "cleMaximumOfAllPixelsKernel.h" 
// #include "cleGreaterConstantKernel.h" 
// #include "cleMaximumXProjectionKernel.h" 
#include "cleAbsoluteKernel.h" 
// #include "cleSumXProjectionKernel.h" 
// #include "cleReplaceIntensityKernel.h" 
// #include "cleCloseIndexGapsInLabelMapKernel.h" 
// #include "cleSetColumnKernel.h" 
// #include "cleSmallerKernel.h" 
// #include "cleGreaterKernel.h" 
// #include "cleMinimumXProjectionKernel.h" 
#include "cleMinimumBoxKernel.h" 
// #include "cleFlagExistingLabelsKernel.h" 
// #include "cleDifferenceOfGaussianKernel.h" 
#include "cleGaussianBlurKernel.h" 
// #include "cleSmallerConstantKernel.h" 
// #include "cleMaximumYProjectionKernel.h" 
#include "cleSeparableKernel.h" 
#include "cleMaximumBoxKernel.h" 
// #include "cleErodeSphereKernel.h" 
#include "cleMeanSphereKernel.h" 
// #include "cleNonzeroMinimumBoxKernel.h" 
// #include "cleSobelKernel.h" 
// #include "cleEqualConstantKernel.h" 
// #include "cleReplaceIntensitiesKernel.h" 
#include "cleExecuteSeparableKernel.h" 
// #include "cleNotEqualConstantKernel.h" 
// #include "cleSumReductionXKernel.h" 
// #include "cleMinimumZProjectionKernel.h" 
// #include "cleNotEqualKernel.h" 



#endif //__cleKernelList_h
