name: CI

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:

  build:
    name: ${{ matrix.os }}-${{ matrix.cxx }}-build
    runs-on: ${{ matrix.os }}

    # For Windows msvc, for Linux and macOS let's use the clang compiler, use gcc for Linux.
    strategy:
      fail-fast: false
      matrix:
        name: [ubuntu-gcc, macos-clang, windows-msvc]
        include:
          - name: windows-msvc
            os: windows-latest
            triplet: x64-windows
            cxx: cl.exe
            cc: cl.exe
          - name: ubuntu-gcc
            os: ubuntu-latest
            triplet: x64-linux          
            cxx: g++
            cc: gcc  
          - name: macos-clang
            os: macos-latest
            triplet: x64-osx
            cxx: clang++
            cc: clang

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true 

      - name: Install Dependencies
        if: ${{ matrix.name }} == ubuntu-gcc
        run: |
          sudo apt update
          sudo apt install -y ocl-icd-opencl-dev libtiff-dev

      - name: Install cmake
        uses: lukka/get-cmake@latest

      # run CMake+Ninja
      - name: Run CMake+Ninja
        uses: lukka/run-cmake@v2
        id: runcmake
        with:
          cmakeGenerator: 'Ninja'  
          cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          useVcpkgToolchainFile: true
          buildWithCMakeArgs: '-- -v'
          buildDirectory: '${{ runner.workspace }}/build/ninja/'  


