name: CI

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:

  build:
    name: ${{ matrix.os }}-${{ matrix.cxx }}-build-and-test
    runs-on: ${{ matrix.os }}

    # For Windows msvc, for Linux and macOS let's use the clang compiler, use gcc for Linux.
    strategy:
      fail-fast: false
      matrix:
        name: [ubuntu-gcc, ubuntu-clang, macos-clang, windows-msvc]
        include:
          - name: windows-msvc
            os: windows-latest
            cxx: cl.exe
            cc: cl.exe
          - name: ubuntu-clang
            os: ubuntu-latest
            cxx: clang++
            cc: clang
          - name: ubuntu-gcc
            os: ubuntu-latest
            cxx: g++
            cc: gcc            
          - name: macos-clang
            os: macos-latest
            cxx: clang++
            cc: clang

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true 

      - name: Install Dependencies
        if: ${{ matrix.os }} == ubuntu-latest
        uses: ryankurte/action-apt@v0.1.0
        with: 
          packages: "libtiff-dev"

      - name: Install cmake
        uses: lukka/get-cmake@latest

      # run CMake+Ninja
      - name: Run CMake+Ninja
        uses: lukka/run-cmake@v2
        id: runcmake
        with:
          cmakeGenerator: 'Ninja'  
          cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          useVcpkgToolchainFile: true
          buildWithCMakeArgs: '-- -v'
          buildDirectory: '${{ runner.workspace }}/build/ninja/'  


