name: MacOS-build

on: [push]

env:
  BUILD_TYPE: Release

jobs:

  build:
    name: ${{ matrix.os }}-${{ matrix.cxx }}-build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        name: [macos]
        include:
          - name: macos-clang
            os: macos-latest
            triplet: x64-osx
            cxx: clang++
            cc: clang

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true 

      - name: Install cmake
        uses: lukka/get-cmake@latest

      - name: Run CMake+Ninja
        uses: lukka/run-cmake@v2
        id: runcmake
        with:
          cmakeGenerator: 'Ninja'  
          cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          useVcpkgToolchainFile: true
          buildWithCMakeArgs: '-- -v'
          buildDirectory: '${{ runner.workspace }}/build/ninja/'  


