name: MacOS-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:

  build:
    
    name: ${{ matrix.os }}-${{ matrix.cxx }}-build-and-test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [macos-clang]
        include:
          - name: macos-clang
            os: macos-latest
            cxx: clang++
            cc: clang

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true 

      - name: Install Dependencies
        if: matrix.name == 'ubuntu-gcc'
        run: |
          sudo apt update
          sudo apt install -y ocl-icd-opencl-dev libtiff-dev

      - name: Install cmake
        uses: lukka/get-cmake@latest

      - name: Run CMake+Ninja
        uses: lukka/run-cmake@v2
        id: runcmake
        with:
          cmakeGenerator: 'Ninja'  
          cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          useVcpkgToolchainFile: true
          buildWithCMakeArgs: '-- -v'
          buildDirectory: '${{ runner.workspace }}/build/ninja/'  


