name: Ubuntu-build

on: [push]

env:
  BUILD_TYPE: Release

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true 

      - if: ${{ matrix.os }} == ubuntu-latest
        name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y ocl-icd-opencl-dev libtiff-dev

      - name: Install cmake
        uses: lukka/get-cmake@latest

      - name: Run CMake+Ninja
        uses: lukka/run-cmake@v2
        id: runcmake
        with:
          cmakeGenerator: 'Ninja'  
          cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          useVcpkgToolchainFile: true
          buildWithCMakeArgs: '-- -v'
          buildDirectory: '${{ runner.workspace }}/build/ninja/'  


