name: Windows-build

on: [push]
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]


env:
  BUILD_TYPE: Release

jobs:

  build:

    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true 

      - name: Install cmake
        uses: lukka/get-cmake@latest

      - name: Instal MSCV
        uses: ilammy/msvc-dev-cmd@v1

      - name: Run CMake+MSVC
        uses: lukka/run-cmake@v2
        id: runcmake
        with:
          cmakeGenerator: VS19Win64  
          cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          useVcpkgToolchainFile: true
          buildWithCMakeArgs: '-- -v'
          buildDirectory: '${{ runner.workspace }}/build/msvc/'  


